export default interface statsGridProps {
    runs: number,
    batAvg: number,
    str: number,
    hs: number,
    wkts: number,
    eco: number,
    innings: number,
    bf: number,
    fours: number,
    sixes: number,
    nos: number,
    threeWi: number,
    bbm: string,
    games: number,
    bowlInnings: number,
}